//! LSP feature catalog and compliance tracking
//!
//! This module exposes the generated LSP feature catalog and helper APIs for
//! mapping advertised capabilities into feature IDs.

/// Auto-generated feature catalog from `features.toml`.
#[allow(clippy::all)]
pub mod catalog {
    // Generated by build.rs into the library crate's OUT_DIR
    include!(concat!(env!("OUT_DIR"), "/feature_catalog.rs"));
}

// Re-export the main functions for convenience
pub use catalog::{LSP_VERSION, VERSION};
pub use catalog::{advertised_features, compliance_percent, has_feature};

/// Get features catalog as JSON
pub fn to_json() -> String {
    serde_json::json!({
        "version": VERSION,
        "lsp_version": LSP_VERSION,
        "compliance_percent": compliance_percent(),
        "advertised": advertised_features(),
    })
    .to_string()
}
