changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## [{{.VersionNoPrefix}}] - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
kinds:
  - label: Added
    key: added
    auto: minor
  - label: Changed
    key: changed
    auto: minor
  - label: Deprecated
    key: deprecated
    auto: minor
  - label: Removed
    key: removed
    auto: minor
  - label: Fixed
    key: fixed
    auto: patch
  - label: Security
    key: security
    auto: patch
  - label: Documentation
    key: documentation
    auto: patch
  - label: Internal
    key: internal
    auto: patch
newlines:
  afterChangelogHeader: 1
  afterChangelogVersion: 1
  beforeKind: 1
  afterKind: 1
  endOfVersion: 1
body:
  minLength: 10
  maxLength: 600
