//! CPAN corpus acquisition, sweep, and ratchet management
//!
//! Provides sub-commands for:
//! - `fetch-list` — query MetaCPAN for top 1000 distributions by reverse dependency count
//! - `install` — install distributions into a local lib directory via `cpanm`
//! - `sweep` — run parser corpus sweep against installed CPAN modules
//! - `ratchet` — auto-append newly-clean modules to the CPAN manifest

use color_eyre::eyre::{Context, Result};
use serde::Deserialize;
use std::collections::BTreeSet;
use std::fs;
use std::io::{BufRead, Write};
use std::path::{Path, PathBuf};
use std::process::Command;

use super::parser_corpus_sweep;

/// Default path for the pinned distribution list
const DIST_LIST_PATH: &str = ".ci/cpan-top-1000-distributions.txt";
/// Default path for the CPAN known-clean manifest
const CPAN_MANIFEST_PATH: &str = ".ci/cpan-corpus-manifest.txt";
/// Default path for the full CPAN corpus baseline report
const CPAN_BASELINE_PATH: &str = ".ci/cpan-corpus-baseline.json";
/// Default install target directory
const CPAN_INSTALL_DIR: &str = "target/cpan-corpus";
/// Standalone cpanm bootstrap URL
const CPANM_STANDALONE_URL: &str = "https://cpanmin.us";
/// MetaCPAN API endpoint for distribution search (sorted by river.immediate)
const METACPAN_API: &str = "https://fastapi.metacpan.org/v1/distribution/_search";

/// Configuration for cpan-corpus sub-commands
#[derive(Debug, Clone)]
pub struct CpanCorpusConfig {
    /// Path to the distribution list file
    pub dist_list: PathBuf,
    /// Path to the CPAN corpus manifest
    pub manifest: PathBuf,
    /// Local install directory for CPAN modules
    pub install_dir: PathBuf,
    /// Number of distributions to fetch (default 1000)
    pub top_n: usize,
    /// Verbose output
    pub verbose: bool,
}

impl Default for CpanCorpusConfig {
    fn default() -> Self {
        Self {
            dist_list: PathBuf::from(DIST_LIST_PATH),
            manifest: PathBuf::from(CPAN_MANIFEST_PATH),
            install_dir: PathBuf::from(CPAN_INSTALL_DIR),
            top_n: 1000,
            verbose: false,
        }
    }
}

// --------------------------------------------------------------------------
// MetaCPAN response types
// --------------------------------------------------------------------------

#[derive(Deserialize)]
struct MetaCpanResponse {
    hits: MetaCpanHits,
}

#[derive(Deserialize)]
struct MetaCpanHits {
    hits: Vec<MetaCpanHit>,
}

#[derive(Deserialize)]
struct MetaCpanHit {
    _source: MetaCpanRelease,
}

#[derive(Deserialize)]
struct MetaCpanRelease {
    name: String,
}

// --------------------------------------------------------------------------
// fetch-list
// --------------------------------------------------------------------------

/// Query MetaCPAN for the top N distributions by reverse dependency count
/// and write them to the distribution list file.
pub fn fetch_list(config: &CpanCorpusConfig) -> Result<()> {
    println!("Fetching top {} distributions from MetaCPAN...", config.top_n);

    let query_body = serde_json::json!({
        "size": config.top_n,
        "query": { "match_all": {} },
        "sort": [{ "river.immediate": { "order": "desc" } }],
        "_source": ["name"]
    });

    let output = Command::new("curl")
        .args([
            "-s",
            "-X",
            "POST",
            METACPAN_API,
            "-H",
            "Content-Type: application/json",
            "-d",
            &query_body.to_string(),
        ])
        .output()
        .context("Failed to run curl — is curl installed?")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(color_eyre::eyre::eyre!("curl failed: {}", stderr));
    }

    let response: MetaCpanResponse =
        serde_json::from_slice(&output.stdout).context("Failed to parse MetaCPAN response")?;

    let distributions: Vec<&str> =
        response.hits.hits.iter().map(|h| h._source.name.as_str()).collect();

    println!("Got {} distributions from MetaCPAN", distributions.len());

    // Write to file
    if let Some(parent) = config.dist_list.parent() {
        fs::create_dir_all(parent).context("Failed to create directory for distribution list")?;
    }

    let mut file = fs::File::create(&config.dist_list)
        .with_context(|| format!("Failed to create {}", config.dist_list.display()))?;

    writeln!(file, "# CPAN top {} distributions by reverse dependency count", config.top_n)?;
    writeln!(file, "# Auto-generated by: cargo xtask cpan-corpus fetch-list")?;
    writeln!(file, "# Source: {METACPAN_API}")?;
    writeln!(file, "# Date: {}", chrono::Utc::now().to_rfc3339())?;
    writeln!(file, "#")?;

    for dist in &distributions {
        writeln!(file, "{dist}")?;
    }

    println!("Wrote {} distributions to {}", distributions.len(), config.dist_list.display());
    Ok(())
}

// --------------------------------------------------------------------------
// install
// --------------------------------------------------------------------------

/// Read the distribution list and install each via cpanm into a local lib.
pub fn install(config: &CpanCorpusConfig) -> Result<()> {
    let mut distributions = read_dist_list(&config.dist_list)?;
    if distributions.is_empty() {
        println!(
            "Distribution list is empty: {}. Fetching top {} distributions first...",
            config.dist_list.display(),
            config.top_n
        );
        fetch_list(config)?;
        distributions = read_dist_list(&config.dist_list)?;
    }
    if distributions.is_empty() {
        return Err(color_eyre::eyre::eyre!(
            "Distribution list is still empty after fetch: {}",
            config.dist_list.display(),
        ));
    }

    println!(
        "Installing {} distributions into {}",
        distributions.len(),
        config.install_dir.display()
    );

    fs::create_dir_all(&config.install_dir).context("Failed to create install directory")?;

    let local_lib =
        config.install_dir.canonicalize().unwrap_or_else(|_| config.install_dir.clone());
    let cpanm = resolve_cpanm_launcher(config)?;
    let cpanm_home = cpanm_home_path(&config.install_dir);
    fs::create_dir_all(&cpanm_home).context("Failed to create cpanm cache directory")?;

    // Install in batches to avoid overly long command lines
    let batch_size = 50;
    let mut installed = 0usize;
    let mut failed = 0usize;

    for (batch_idx, chunk) in distributions.chunks(batch_size).enumerate() {
        let batch_num = batch_idx + 1;
        let total_batches = distributions.len().div_ceil(batch_size);
        println!("Batch {batch_num}/{total_batches}: installing {} distributions...", chunk.len());

        let mut cmd = cpanm.command();
        cmd.env("PERL_CPANM_HOME", &cpanm_home);
        cmd.env("PERL_MM_USE_DEFAULT", "1");
        cmd.env("NONINTERACTIVE_TESTING", "1");
        cmd.arg("--notest");
        cmd.arg("--local-lib");
        cmd.arg(local_lib.display().to_string());
        cmd.arg("--quiet");

        for dist in chunk {
            cmd.arg(dist);
        }

        let output = cmd.output().context("Failed to run cpanm")?;

        if output.status.success() {
            installed += chunk.len();
        } else {
            // cpanm may partially succeed; count individual results if verbose
            let stderr = String::from_utf8_lossy(&output.stderr);
            if config.verbose {
                eprintln!("cpanm batch {batch_num} warnings:\n{stderr}");
            }
            // Approximate: some may have installed, some may have failed
            installed += chunk.len().saturating_sub(1);
            failed += 1;
        }
    }

    println!("\nInstall complete: ~{installed} installed, {failed} batches had errors");

    // Write inventory of installed .pm files
    let lib_perl5 = local_lib.join("lib/perl5");
    if lib_perl5.exists() {
        let pm_count = walkdir::WalkDir::new(&lib_perl5)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().is_some_and(|ext| ext == "pm"))
            .count();
        println!("Found {pm_count} .pm files in {}", lib_perl5.display());
    } else {
        println!("Warning: {} not found after install", lib_perl5.display());
    }

    Ok(())
}

#[derive(Debug, Clone)]
enum CpanmLauncher {
    System,
    Bootstrapped(PathBuf),
}

impl CpanmLauncher {
    fn command(&self) -> Command {
        match self {
            Self::System => Command::new("cpanm"),
            Self::Bootstrapped(path) => {
                let mut cmd = Command::new("perl");
                cmd.arg(path);
                cmd
            }
        }
    }
}

fn resolve_cpanm_launcher(config: &CpanCorpusConfig) -> Result<CpanmLauncher> {
    if Command::new("cpanm").arg("--version").output().is_ok() {
        return Ok(CpanmLauncher::System);
    }

    let script_path = bootstrap_cpanm_script(config)?;
    Ok(CpanmLauncher::Bootstrapped(script_path))
}

fn bootstrap_cpanm_path(install_dir: &Path) -> PathBuf {
    install_dir.join("bin").join("cpanm")
}

fn cpanm_home_path(install_dir: &Path) -> PathBuf {
    install_dir.join(".cpanm")
}

fn bootstrap_cpanm_script(config: &CpanCorpusConfig) -> Result<PathBuf> {
    let script_path = bootstrap_cpanm_path(&config.install_dir);
    if script_path.exists() {
        return Ok(script_path);
    }

    if let Some(parent) = script_path.parent() {
        fs::create_dir_all(parent).context("Failed to create cpanm bootstrap directory")?;
    }

    println!("System cpanm not found; bootstrapping standalone cpanm to {}", script_path.display());

    let output = Command::new("curl")
        .args(["-fsSL", CPANM_STANDALONE_URL, "-o"])
        .arg(&script_path)
        .output()
        .context("Failed to run curl for standalone cpanm bootstrap")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(color_eyre::eyre::eyre!(
            "Failed to bootstrap standalone cpanm from {}: {}",
            CPANM_STANDALONE_URL,
            stderr,
        ));
    }

    Ok(script_path)
}

// --------------------------------------------------------------------------
// sweep
// --------------------------------------------------------------------------

/// Run the parser corpus sweep against the installed CPAN corpus.
pub fn sweep(config: &CpanCorpusConfig, output: Option<PathBuf>, enforce: bool) -> Result<()> {
    let lib_perl5 = config.install_dir.join("lib/perl5");
    if !lib_perl5.exists() {
        return Err(color_eyre::eyre::eyre!(
            "CPAN corpus not installed: {} not found. Run `cargo xtask cpan-corpus install` first.",
            lib_perl5.display(),
        ));
    }

    let base_roots = vec![lib_perl5.clone()];
    let corpus_roots = parser_corpus_sweep::resolve_corpus_roots(&base_roots);

    let baseline_path = if enforce {
        let bp = PathBuf::from(CPAN_BASELINE_PATH);
        if bp.exists() {
            Some(bp)
        } else {
            return Err(color_eyre::eyre::eyre!(
                "CPAN baseline missing: {}. Run `cargo xtask cpan-corpus sweep --output {}` or `just cpan-corpus-baseline-update` first.",
                bp.display(),
                CPAN_BASELINE_PATH,
            ));
        }
    } else {
        None
    };

    let sweep_config = parser_corpus_sweep::SweepConfig {
        base_roots: base_roots.clone(),
        corpus_roots: corpus_roots.clone(),
        manifest_path: None,
        manifest_perl5lib: Vec::new(),
        output_path: output,
        baseline_path,
        enforce,
        verbose: config.verbose,
        receipt: true,
    };

    parser_corpus_sweep::run(sweep_config)?;

    if enforce {
        if !config.manifest.exists() {
            return Err(color_eyre::eyre::eyre!(
                "CPAN known-clean manifest missing: {}. Restore the tracked file or seed it with `just cpan-corpus-ratchet` after bootstrap.",
                config.manifest.display(),
            ));
        }

        let manifest_metadata = fs::metadata(&config.manifest)
            .with_context(|| format!("Failed to stat manifest: {}", config.manifest.display()))?;
        if manifest_metadata.len() == 0 {
            return Err(color_eyre::eyre::eyre!(
                "CPAN known-clean manifest is zero-length: {}. Restore the tracked placeholder or seed it with `just cpan-corpus-ratchet`.",
                config.manifest.display(),
            ));
        }

        let manifest_modules = parser_corpus_sweep::parse_manifest(&config.manifest)?;

        if manifest_modules.is_empty() {
            println!(
                "CPAN known-clean manifest is still in bootstrap state; skipping strict clean check ({})",
                config.manifest.display()
            );
        } else {
            println!(
                "\nChecking CPAN known-clean manifest ({} modules)...",
                manifest_modules.len()
            );
            let manifest_sweep = parser_corpus_sweep::SweepConfig {
                base_roots,
                corpus_roots: corpus_roots.clone(),
                manifest_path: Some(config.manifest.clone()),
                manifest_perl5lib: corpus_roots,
                output_path: None,
                baseline_path: None,
                enforce: true,
                verbose: config.verbose,
                receipt: false,
            };
            parser_corpus_sweep::run(manifest_sweep)?;
        }
    }

    Ok(())
}

// --------------------------------------------------------------------------
// ratchet
// --------------------------------------------------------------------------

/// Run a sweep and auto-append newly-clean modules to the manifest.
pub fn ratchet(config: &CpanCorpusConfig) -> Result<()> {
    let lib_perl5 = config.install_dir.join("lib/perl5");
    if !lib_perl5.exists() {
        return Err(color_eyre::eyre::eyre!(
            "CPAN corpus not installed: {} not found. Run `cargo xtask cpan-corpus install` first.",
            lib_perl5.display(),
        ));
    }

    // Run a verbose sweep to get per-file results
    let base_roots = vec![lib_perl5.clone()];
    let corpus_roots = parser_corpus_sweep::resolve_corpus_roots(&base_roots);

    // Write a temp report to capture results
    let report_path = PathBuf::from("target/cpan-corpus-ratchet-report.json");
    if let Some(parent) = report_path.parent() {
        fs::create_dir_all(parent).context("Failed to create report directory")?;
    }

    let sweep_config = parser_corpus_sweep::SweepConfig {
        base_roots,
        corpus_roots,
        manifest_path: None,
        manifest_perl5lib: Vec::new(),
        output_path: Some(report_path.clone()),
        baseline_path: None,
        enforce: false,
        verbose: true,
        receipt: false,
    };

    parser_corpus_sweep::run(sweep_config)?;

    // Read the report to find clean files
    let report_json = fs::read_to_string(&report_path).context("Failed to read sweep report")?;
    let report: parser_corpus_sweep::SweepReport =
        serde_json::from_str(&report_json).context("Failed to parse sweep report")?;

    // Extract module names from clean file paths
    let clean_modules: BTreeSet<String> = report
        .file_results
        .iter()
        .filter(|r| r.status == "clean")
        .filter_map(|r| path_to_module_name(&r.path, &lib_perl5))
        .collect();

    if clean_modules.is_empty() {
        println!("No clean modules found to add to manifest.");
        return Ok(());
    }

    // Read existing manifest entries
    let existing: BTreeSet<String> = if config.manifest.exists() {
        parser_corpus_sweep::parse_manifest(&config.manifest)?.into_iter().collect()
    } else {
        BTreeSet::new()
    };

    let new_modules: BTreeSet<&String> = clean_modules.difference(&existing).collect();

    if new_modules.is_empty() {
        println!("All {} clean modules already in manifest.", clean_modules.len());
        return Ok(());
    }

    println!(
        "Adding {} new clean modules to manifest (total clean: {})",
        new_modules.len(),
        clean_modules.len()
    );

    // Append new modules to manifest
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&config.manifest)
        .with_context(|| format!("Failed to open manifest: {}", config.manifest.display()))?;

    writeln!(file, "#")?;
    writeln!(file, "# Added by ratchet on {}", chrono::Utc::now().to_rfc3339())?;

    for module in &new_modules {
        writeln!(file, "{module}")?;
    }

    println!("Manifest updated: {}", config.manifest.display());

    // Clean up temp report
    let _ = fs::remove_file(&report_path);

    Ok(())
}

// --------------------------------------------------------------------------
// Helpers
// --------------------------------------------------------------------------

/// Read the distribution list, skipping comments and empty lines.
fn read_dist_list(path: &Path) -> Result<Vec<String>> {
    let file = fs::File::open(path)
        .with_context(|| format!("Failed to open distribution list: {}", path.display()))?;
    let reader = std::io::BufReader::new(file);
    let mut distributions = Vec::new();
    for line in reader.lines() {
        let line = line.context("Failed to read line")?;
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        distributions.push(trimmed.to_string());
    }
    Ok(distributions)
}

/// Convert a .pm file path to a Perl module name, relative to the lib directory.
///
/// e.g., `/path/to/lib/perl5/File/Find.pm` → `File::Find`
fn path_to_module_name(file_path: &str, lib_root: &Path) -> Option<String> {
    let path = Path::new(file_path);
    let relative = path.strip_prefix(lib_root).ok()?;

    // Skip architecture-specific subdirs (e.g., x86_64-linux-gnu-thread-multi/)
    let rel_str = relative.to_string_lossy();
    let module_path = if rel_str.contains("auto/") {
        // Skip XS auto directories
        return None;
    } else {
        relative
    };

    let stem = module_path.with_extension("");
    let module_name = stem.to_string_lossy().replace('/', "::");
    Some(module_name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_read_dist_list_parsing() {
        let dir = std::env::temp_dir().join("test_cpan_dist_list");
        let _ = fs::create_dir_all(&dir);
        let path = dir.join("dists.txt");
        fs::write(&path, "# Header comment\n\nMoose\nDBI\n# Another comment\nTry-Tiny\n").ok();
        let dists = read_dist_list(&path).unwrap_or_default();
        assert_eq!(dists, vec!["Moose", "DBI", "Try-Tiny"]);
        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn test_path_to_module_name() {
        let lib = PathBuf::from("/opt/cpan/lib/perl5");
        assert_eq!(
            path_to_module_name("/opt/cpan/lib/perl5/File/Find.pm", &lib),
            Some("File::Find".to_string()),
        );
        assert_eq!(
            path_to_module_name("/opt/cpan/lib/perl5/Moose.pm", &lib),
            Some("Moose".to_string()),
        );
        // auto/ directories should be skipped
        assert_eq!(path_to_module_name("/opt/cpan/lib/perl5/auto/DBI/DBI.so", &lib), None,);
    }

    #[test]
    fn test_path_to_module_name_outside_lib() {
        let lib = PathBuf::from("/opt/cpan/lib/perl5");
        assert_eq!(path_to_module_name("/some/other/path/Foo.pm", &lib), None,);
    }

    #[test]
    fn test_default_config() {
        let config = CpanCorpusConfig::default();
        assert_eq!(config.dist_list, PathBuf::from(".ci/cpan-top-1000-distributions.txt"));
        assert_eq!(config.manifest, PathBuf::from(".ci/cpan-corpus-manifest.txt"));
        assert_eq!(config.install_dir, PathBuf::from("target/cpan-corpus"));
        assert_eq!(config.top_n, 1000);
    }

    #[test]
    fn test_cpan_baseline_path_constant() {
        assert_eq!(CPAN_BASELINE_PATH, ".ci/cpan-corpus-baseline.json");
    }

    #[test]
    fn test_bootstrap_cpanm_path() {
        let install_dir = PathBuf::from("target/cpan-corpus");
        assert_eq!(bootstrap_cpanm_path(&install_dir), install_dir.join("bin").join("cpanm"));
    }

    #[test]
    fn test_cpanm_home_path() {
        let install_dir = PathBuf::from("target/cpan-corpus");
        assert_eq!(cpanm_home_path(&install_dir), install_dir.join(".cpanm"));
    }
}
