//! Task implementations for xtask automation

pub mod bench;
pub mod build_timing;
#[cfg(feature = "parser-tasks")]
pub mod bindings;
pub mod build;
pub mod bump_version;
pub mod check;
pub mod ci;
pub mod ci_audit_workflows;
pub mod ci_measure;
pub mod ci_metrics;
pub mod ci_policy;
pub mod check_toolchain;
pub mod clean;
pub mod ci_hygiene;
pub mod compare;
#[cfg(feature = "legacy")]
pub mod compare_parsers;
#[cfg(feature = "legacy")]
pub mod corpus;
pub mod corpus_audit;
pub mod cpan_corpus;
pub mod dead_code;
pub mod debt_report;
pub mod devex_doctor;
pub mod hook_checks;
pub mod dev;
pub mod doc;
pub mod doc_claims;
pub mod check_version_sync;
pub mod e2e_validate;
pub mod forensics;
pub mod hardening;
pub mod edge_cases;
pub mod features;
pub mod inject_sha_assets;
pub mod update_homebrew;
pub mod fmt;
pub mod benchmarks;
pub mod github;
pub mod gates;
pub mod forbid_fatal_constructs;
#[cfg(feature = "parser-tasks")]
pub mod highlight;
pub mod ignored_tests;
pub mod populate_book;
pub mod parse_rust;
pub mod parser_corpus_sweep;
pub mod parser_matrix;
pub mod publish;
pub mod prep_crates_io_launch;
pub mod publication_facts;
pub mod publish_receipts;
pub mod receipts;
pub mod release;
pub mod release_turnkey;
pub mod swarm_summary;
pub mod srp_microcrates;
pub mod targeted_checks;
pub mod test;
pub mod test_lsp;
pub mod validate_workspace_exclusions;
pub mod worktrees;
pub mod unwired_scan;
pub mod update_status;
