use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use color_eyre::eyre::{Context, Result};
use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::utils;

const DEFAULT_FIXTURES: &str = "xtask/fixtures/semantic_scorecard/fixtures.toml";
const DEFAULT_OUTPUT: &str = "target/receipts/metrics/semantic_scorecard.json";
const DEFAULT_STATUS_MD: &str = "docs/project/status/semantic_scorecard.md";

#[derive(Debug, Clone, Deserialize)]
struct FixtureManifest {
    fixture_family: Vec<FixtureFamily>,
    metric: Vec<MetricDefinition>,
}

#[derive(Debug, Clone, Deserialize)]
struct FixtureFamily {
    id: String,
    description: String,
    status: String,
}

#[derive(Debug, Clone, Deserialize)]
struct MetricDefinition {
    name: String,
    unit: String,
    status: String,
    notes: String,
}

#[derive(Debug, Clone, Serialize)]
struct SemanticScorecardArtifact {
    schema_version: u32,
    fixture_count: usize,
    metric_count: usize,
    fixture_status_counts: BTreeMap<String, usize>,
    metric_status_counts: BTreeMap<String, usize>,
    fixtures: Vec<FixtureFamilyOut>,
    metrics: Vec<MetricDefinitionOut>,
}

#[derive(Debug, Clone, Serialize)]
struct FixtureFamilyOut {
    id: String,
    description: String,
    status: String,
}

#[derive(Debug, Clone, Serialize)]
struct MetricDefinitionOut {
    name: String,
    unit: String,
    status: String,
    notes: String,
}

pub fn run(fixtures: Option<PathBuf>, output: Option<PathBuf>, status_md: Option<PathBuf>) -> Result<()> {
    let root = utils::project_root()?;
    let fixture_path = root.join(fixtures.unwrap_or_else(|| PathBuf::from(DEFAULT_FIXTURES)));
    let output_path = root.join(output.unwrap_or_else(|| PathBuf::from(DEFAULT_OUTPUT)));
    let status_path = root.join(status_md.unwrap_or_else(|| PathBuf::from(DEFAULT_STATUS_MD)));

    let artifact = load_artifact(&fixture_path)?;

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&output_path, serde_json::to_string_pretty(&artifact)?)
        .with_context(|| format!("writing {}", output_path.display()))?;

    if let Some(parent) = status_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    fs::write(&status_path, render_status_markdown(&artifact))
        .with_context(|| format!("writing {}", status_path.display()))?;

    println!(
        "{}",
        serde_json::to_string_pretty(&json!({
            "status": "ok",
            "scorecard": "semantic",
            "fixture_manifest": fixture_path,
            "output": output_path,
            "status_md": status_path,
            "fixture_count": artifact.fixture_count,
            "metric_count": artifact.metric_count
        }))?
    );

    Ok(())
}

fn load_artifact(path: &Path) -> Result<SemanticScorecardArtifact> {
    let raw = fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let mut manifest: FixtureManifest = toml::from_str(&raw)
        .with_context(|| format!("parsing {}", path.display()))?;

    manifest.fixture_family.sort_by(|a, b| a.id.cmp(&b.id));
    manifest.metric.sort_by(|a, b| a.name.cmp(&b.name));

    let fixture_status_counts = summarize(manifest.fixture_family.iter().map(|x| x.status.as_str()));
    let metric_status_counts = summarize(manifest.metric.iter().map(|x| x.status.as_str()));

    Ok(SemanticScorecardArtifact {
        schema_version: 1,
        fixture_count: manifest.fixture_family.len(),
        metric_count: manifest.metric.len(),
        fixture_status_counts,
        metric_status_counts,
        fixtures: manifest
            .fixture_family
            .into_iter()
            .map(|item| FixtureFamilyOut {
                id: item.id,
                description: item.description,
                status: item.status,
            })
            .collect(),
        metrics: manifest
            .metric
            .into_iter()
            .map(|item| MetricDefinitionOut {
                name: item.name,
                unit: item.unit,
                status: item.status,
                notes: item.notes,
            })
            .collect(),
    })
}

fn summarize<'a>(items: impl Iterator<Item = &'a str>) -> BTreeMap<String, usize> {
    let mut counts = BTreeMap::new();
    for item in items {
        *counts.entry(item.to_string()).or_insert(0) += 1;
    }
    counts
}

fn render_status_markdown(artifact: &SemanticScorecardArtifact) -> String {
    let mut text = String::new();
    text.push_str("# Semantic Scorecard (Harness Baseline)\n\n");
    text.push_str("This file is generated by `cargo xtask semantic-scorecard`.\n\n");
    text.push_str("## Summary\n\n");
    text.push_str(&format!("- Fixture families: {}\n", artifact.fixture_count));
    text.push_str(&format!("- Metrics defined: {}\n\n", artifact.metric_count));
    text.push_str("## How to extend\n\n");
    text.push_str("- Add a new `[[fixture_family]]` row to `xtask/fixtures/semantic_scorecard/fixtures.toml`.\n");
    text.push_str("- Add or update `[[metric]]` rows with `status = \"implemented\"` when a metric becomes live.\n");
    text.push_str("- Re-run `cargo xtask semantic-scorecard` and commit both JSON + markdown outputs.\n\n");
    text.push_str("## Fixture families\n\n");
    for fixture in &artifact.fixtures {
        text.push_str(&format!("- `{}` — {} ({})\n", fixture.id, fixture.description, fixture.status));
    }
    text.push_str("\n## Metrics\n\n");
    for metric in &artifact.metrics {
        text.push_str(&format!(
            "- `{}` [{}] — {} ({})\n",
            metric.name, metric.unit, metric.status, metric.notes
        ));
    }
    text
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn fixture_manifest_load_is_deterministic() -> Result<()> {
        let root = utils::project_root()?;
        let path = root.join(DEFAULT_FIXTURES);
        let a = load_artifact(&path)?;
        let b = load_artifact(&path)?;
        assert_eq!(serde_json::to_string(&a)?, serde_json::to_string(&b)?);
        assert_eq!(a.fixture_count, 12);
        assert_eq!(a.metric_count, 11);
        Ok(())
    }
}
