//! Feature contracts (absorbed from perl-lsp-feature-contracts).
//!
//! This module will contain the actual feature contract definitions
//! and build-time generated constants once the builder implements Wave F.

// This module includes code generated by build.rs
include!(concat!(env!("OUT_DIR"), "/feature_contracts.rs"));
