/// Feature catalog and LSP compliance tracking
/// This module exports the auto-generated feature catalog from build.rs
/// and provides utilities for mapping capabilities to feature IDs

#[allow(clippy::all)]
pub mod catalog {
    // Generated by build.rs into the library crate's OUT_DIR
    include!(concat!(env!("OUT_DIR"), "/feature_catalog.rs"));
}

pub mod map;

// Re-export the main functions for convenience
pub use catalog::{advertised_features, compliance_percent, has_feature};
pub use catalog::{LSP_VERSION, VERSION};

/// Get features catalog as JSON
pub fn to_json() -> String {
    serde_json::json!({
        "version": VERSION,
        "lsp_version": LSP_VERSION,
        "compliance_percent": compliance_percent(),
        "advertised": advertised_features(),
    }).to_string()
}