#!/usr/bin/env python3
"""Find workspace SRP microcrates and emit a grouped markdown report.

Heuristic:
1) Crates in known microcrate families are always SRP candidates.
2) Additional crates become SRP candidates when their README or lib-level docs
   explicitly describe a narrow/single responsibility.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
import tomllib

FAMILY_PREFIXES: tuple[str, ...] = (
    "perl-module-",
    "perl-lsp-feature-",
    "perl-dap-",
    "perl-workspace-",
    "perl-ts-",
)

SRP_KEYWORDS: tuple[str, ...] = (
    "single responsibility",
    "one responsibility",
    "narrow responsibility",
    "standalone microcrate",
    "tiny microcrate",
    "internal microcrate",
    "leaf crate",
)


def load_crate_name(cargo_toml: Path) -> str | None:
    data = tomllib.loads(cargo_toml.read_text(encoding="utf-8"))
    package = data.get("package", {})
    name = package.get("name")
    return name if isinstance(name, str) else None


def read_text_if_exists(path: Path) -> str:
    if path.exists() and path.is_file():
        return path.read_text(encoding="utf-8", errors="ignore").lower()
    return ""


def infer_family(crate: str) -> str:
    for prefix in FAMILY_PREFIXES:
        if crate.startswith(prefix):
            return prefix.rstrip("-")
    return "core-srp"


def is_srp_candidate(crate_name: str, crate_dir: Path) -> bool:
    if any(crate_name.startswith(prefix) for prefix in FAMILY_PREFIXES):
        return True

    searchable = "\n".join(
        [
            read_text_if_exists(crate_dir / "README.md"),
            read_text_if_exists(crate_dir / "src" / "lib.rs"),
        ]
    )
    return any(keyword in searchable for keyword in SRP_KEYWORDS)


def collect_srp_crates(workspace_root: Path) -> dict[str, list[str]]:
    crates_dir = workspace_root / "crates"
    grouped: dict[str, list[str]] = defaultdict(list)

    for cargo_toml in sorted(crates_dir.glob("*/Cargo.toml")):
        crate_name = load_crate_name(cargo_toml)
        if not crate_name:
            continue
        crate_dir = cargo_toml.parent
        if is_srp_candidate(crate_name, crate_dir):
            grouped[infer_family(crate_name)].append(crate_name)

    for family in grouped:
        grouped[family].sort()
    return dict(sorted(grouped.items()))


def render_markdown(grouped: dict[str, list[str]]) -> str:
    total = sum(len(crates) for crates in grouped.values())
    lines = [
        "# SRP Microcrates",
        "",
        "Generated by `python3 scripts/find_srp_microcrates.py --write docs/SRP_MICROCRATES.md`.",
        "",
        "## Summary",
        "",
        f"- Total SRP microcrate candidates: **{total}**",
    ]

    for family, crates in grouped.items():
        lines.append(f"- `{family}`: **{len(crates)}**")

    lines.extend(["", "## Grouped Crates", ""])

    for family, crates in grouped.items():
        lines.append(f"### `{family}`")
        lines.append("")
        for crate in crates:
            lines.append(f"- `{crate}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace-root",
        default=".",
        help="Path to workspace root (default: current directory)",
    )
    parser.add_argument("--write", help="Write markdown report to this path")
    args = parser.parse_args()

    workspace_root = Path(args.workspace_root).resolve()
    grouped = collect_srp_crates(workspace_root)
    report = render_markdown(grouped)

    if args.write:
        output_path = (workspace_root / args.write).resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(report, encoding="utf-8")
    else:
        print(report)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
