//! Tree-sitter Perl grammar binding (C FFI).
//!
//! This crate is the conventional C/tree-sitter reference implementation for
//! Perl, maintained alongside the native v3 Rust parser ([`perl-parser`]) for
//! compatibility testing and comparison. It vendors a snapshot of the upstream
//! [tree-sitter-perl] C grammar (`parser.c` + `scanner.c`) under `c-src/` and
//! exposes it via a hand-written FFI declaration — no `bindgen` or `libclang`
//! dependency is required to build.
//!
//! ## Relation to `tree-sitter-perl-rs`
//!
//! [`tree-sitter-perl-rs`] is a thin facade over the native v3 Rust parser and
//! is the recommended choice for new Rust projects. This crate (`tree-sitter-perl-c`)
//! should be preferred when:
//!
//! - **Compatibility testing** — comparing parse output against the upstream
//!   C reference grammar.
//! - **Non-Rust tree-sitter tooling** — the C grammar snapshot can be used as
//!   a build dependency for language bindings in other languages.
//! - **Baseline benchmarking** — measuring parse throughput of the C grammar
//!   against the native v3 parser.
//!
//! ## Build requirements
//!
//! Only a C compiler is required (e.g., `cc`/`gcc`/`clang` on Linux/macOS,
//! MSVC or MinGW on Windows). No `libclang` or `bindgen` toolchain is needed.
//!
//! ## Quick start
//!
//! ```rust
//! use tree_sitter_perl_c::parse_perl_code;
//!
//! let tree = parse_perl_code("my $x = 42;").unwrap();
//! assert!(!tree.root_node().has_error());
//! println!("{}", tree.root_node().to_sexp());
//! ```
//!
//! [tree-sitter-perl]: https://github.com/tree-sitter-perl/tree-sitter-perl
//! [`perl-parser`]: https://docs.rs/perl-parser
//! [`tree-sitter-perl-rs`]: https://docs.rs/tree-sitter-perl-rs

use std::{fmt, path::Path};
use tree_sitter::{Language, Parser};

/// Typed parse/setup errors for the C tree-sitter Perl backend.
#[derive(Debug)]
pub enum ParseError {
    /// The linked tree-sitter runtime is incompatible with this grammar.
    Language(tree_sitter::LanguageError),
    /// Tree-sitter returned `None` from parse (typically timeout/cancel).
    ParseReturnedNone,
    /// Source file I/O failed before parsing could begin.
    Io(std::io::Error),
}

impl fmt::Display for ParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Language(error) => write!(f, "failed to configure parser language: {error}"),
            Self::ParseReturnedNone => {
                f.write_str("tree-sitter returned no parse tree (cancelled or timed out)")
            }
            Self::Io(error) => write!(f, "failed to read Perl source file: {error}"),
        }
    }
}

impl std::error::Error for ParseError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Language(error) => Some(error),
            Self::Io(error) => Some(error),
            Self::ParseReturnedNone => None,
        }
    }
}

/// Returns the tree-sitter [`Language`] for Perl (C grammar).
///
/// Use this to configure a [`tree_sitter::Parser`] or to create query objects
/// that target the Perl grammar.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::language;
/// use tree_sitter::Parser;
///
/// let lang = language();
/// let mut parser = Parser::new();
/// parser.set_language(&lang).unwrap();
/// ```
pub fn language() -> Language {
    // SAFETY: `tree_sitter_perl` is generated by tree-sitter-cli and linked via `build.rs`.
    // It returns a valid, 'static `Language` value representing the Perl grammar. The function
    // has no preconditions on the calling thread, takes no arguments, holds no borrows, and
    // cannot cause aliasing or memory-safety issues. Soundness depends on the build script
    // linking the correct, ABI-compatible parser object, which cc::Build in build.rs guarantees.
    unsafe { tree_sitter_perl() }
}

/// Creates a [`tree_sitter::Parser`] configured for Perl.
///
/// Returns an error if the language version is incompatible with the linked
/// tree-sitter runtime (this should not happen in practice).
///
/// Prefer this over [`create_parser`] in new code — it surfaces errors
/// explicitly.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::try_create_parser;
///
/// let mut parser = try_create_parser().unwrap();
/// let tree = parser.parse("my $x = 1;", None).unwrap();
/// assert!(!tree.root_node().has_error());
/// ```
pub fn try_create_parser() -> Result<Parser, tree_sitter::LanguageError> {
    let mut parser = Parser::new();
    parser.set_language(&language())?;
    Ok(parser)
}

/// Parses a Perl source string and returns a typed error on failure.
///
/// This is the strongly typed variant of [`parse_perl_code`].
pub fn try_parse_perl_code(code: &str) -> Result<tree_sitter::Tree, ParseError> {
    let mut parser = try_create_parser().map_err(ParseError::Language)?;
    parser.parse(code, None).ok_or(ParseError::ParseReturnedNone)
}

/// Reads a file from `path` and parses it as Perl source with typed errors.
///
/// This is the strongly typed variant of [`parse_perl_file`].
pub fn try_parse_perl_file<P: AsRef<Path>>(path: P) -> Result<tree_sitter::Tree, ParseError> {
    let code = std::fs::read_to_string(path).map_err(ParseError::Io)?;
    try_parse_perl_code(&code)
}

/// Creates a [`tree_sitter::Parser`] configured for Perl, silently ignoring
/// language-set errors.
///
/// This is a compatibility shim. Prefer [`try_create_parser`] in new code so
/// that version mismatches are not swallowed.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::create_parser;
///
/// let parser = create_parser();
/// assert!(parser.language().is_some());
/// ```
pub fn create_parser() -> Parser {
    let mut parser = Parser::new();
    let _ = parser.set_language(&language());
    parser
}

/// Parses a Perl source string and returns the resulting [`tree_sitter::Tree`].
///
/// # Errors
///
/// Returns an error if the parser cannot be initialised (version mismatch) or
/// if tree-sitter returns `None` from `parse` (cancelled or timed out).
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::parse_perl_code;
///
/// let tree = parse_perl_code("my $x = 42;").unwrap();
/// assert!(!tree.root_node().has_error());
/// ```
pub fn parse_perl_code(code: &str) -> Result<tree_sitter::Tree, Box<dyn std::error::Error>> {
    try_parse_perl_code(code).map_err(Into::into)
}

/// Reads a file from `path` and parses it as Perl source.
///
/// # Errors
///
/// Returns an error if the file cannot be read or if parsing fails (see
/// [`parse_perl_code`]).
pub fn parse_perl_file<P: AsRef<Path>>(
    path: P,
) -> Result<tree_sitter::Tree, Box<dyn std::error::Error>> {
    try_parse_perl_file(path).map_err(Into::into)
}

/// Returns the scanner backend identifier for this crate.
///
/// Always returns `"c-scanner"`. Useful when code needs to distinguish between
/// this crate and the Rust-native [`tree-sitter-perl-rs`] backend.
///
/// [`tree-sitter-perl-rs`]: https://docs.rs/tree-sitter-perl-rs
pub fn get_scanner_config() -> &'static str {
    "c-scanner"
}

#[cfg(test)]
mod tests {
    use super::*;
    use tree_sitter::{Query, QueryCursor, StreamingIterator};

    const INJECTIONS_QUERY: &str = include_str!("../../../tree-sitter-perl/queries/injections.scm");

    fn capture_text<'a>(
        query: &'a Query,
        code: &'a str,
        capture: tree_sitter::QueryCapture<'a>,
    ) -> Option<(&'a str, &'a str)> {
        let name = query.capture_names().get(capture.index as usize)?;
        let text = capture.node.utf8_text(code.as_bytes()).ok()?;
        Some((*name, text))
    }

    #[test]
    fn test_language_loading() {
        let lang = language();
        let count = lang.node_kind_count();
        println!("C implementation node kind count: {}", count);
        // Language is valid if we can get its node kind count
        assert!(count > 0);
    }

    #[test]
    fn test_basic_parsing() -> Result<(), Box<dyn std::error::Error>> {
        let code = "my $var = 'hello';";
        let tree = parse_perl_code(code)?;
        assert!(!tree.root_node().has_error());
        Ok(())
    }

    #[test]
    fn test_parser_creation() {
        let parser = create_parser();
        assert!(parser.language().is_some());
    }

    #[test]
    fn test_try_parse_perl_file_returns_io_error_for_missing_file() {
        let missing_path =
            std::env::temp_dir().join("tree_sitter_perl_c_missing_file_please_ignore.pl");
        let result = try_parse_perl_file(&missing_path);
        assert!(matches!(result, Err(ParseError::Io(_))));
    }

    #[test]
    fn test_inline_cpp_injection_query_matches_heredoc_body()
    -> Result<(), Box<dyn std::error::Error>> {
        let code = "use Inline CPP => <<'END_CPP';\n#include <string>\nclass Greet {};\nEND_CPP\n";
        let tree = parse_perl_code(code)?;
        let query = Query::new(&language(), INJECTIONS_QUERY)?;
        let mut cursor = QueryCursor::new();

        let mut matched = false;
        let mut matches = cursor.matches(&query, tree.root_node(), code.as_bytes());
        while let Some(m) = matches.next() {
            let mut saw_inline_package = false;
            let mut saw_inline_language = false;
            let mut saw_injection_content = false;

            for capture in m.captures {
                if let Some((name, text)) = capture_text(&query, code, *capture) {
                    match name {
                        "inline.package" => saw_inline_package = text == "Inline",
                        "inline.language" => saw_inline_language = text == "CPP",
                        "injection.content" => {
                            saw_injection_content = capture.node.kind() == "heredoc_content"
                                && text.contains("#include <string>");
                        }
                        _ => {}
                    }
                }
            }

            if saw_inline_package && saw_inline_language && saw_injection_content {
                matched = true;
                break;
            }
        }

        assert!(matched, "expected Inline::CPP heredoc to match the injection query");
        Ok(())
    }
}

// SAFETY: See the SAFETY comment on the `language()` function above.
// This is the only unsafe code in the crate — the single FFI symbol we need
// from the compiled C grammar. No bindgen is used; the declaration is
// hand-written to avoid a libclang build dependency.
unsafe extern "C" {
    fn tree_sitter_perl() -> Language;
}
