//! Tree-sitter Perl grammar binding (C FFI).
//!
//! This crate is the conventional C/tree-sitter reference implementation for
//! Perl, maintained alongside the native v3 Rust parser ([`perl-parser`]) for
//! compatibility testing and comparison. It vendors a snapshot of the upstream
//! [tree-sitter-perl] C grammar (`parser.c` + `scanner.c`) under `c-src/` and
//! exposes it via a hand-written FFI declaration — no `bindgen` or `libclang`
//! dependency is required to build.
//!
//! ## Relation to `tree-sitter-perl-rs`
//!
//! [`tree-sitter-perl-rs`] is a thin facade over the native v3 Rust parser and
//! is the recommended choice for new Rust projects. This crate (`tree-sitter-perl-c`)
//! should be preferred when:
//!
//! - **Compatibility testing** — comparing parse output against the upstream
//!   C reference grammar.
//! - **Non-Rust tree-sitter tooling** — the C grammar snapshot can be used as
//!   a build dependency for language bindings in other languages.
//! - **Baseline benchmarking** — measuring parse throughput of the C grammar
//!   against the native v3 parser.
//!
//! ## Build requirements
//!
//! Only a C compiler is required (e.g., `cc`/`gcc`/`clang` on Linux/macOS,
//! MSVC or MinGW on Windows). No `libclang` or `bindgen` toolchain is needed.
//!
//! ## Quick start
//!
//! ```rust
//! use tree_sitter_perl_c::parse_perl_code;
//!
//! let tree = parse_perl_code("my $x = 42;").unwrap();
//! assert!(!tree.root_node().has_error());
//! println!("{}", tree.root_node().to_sexp());
//! ```
//!
//! [tree-sitter-perl]: https://github.com/tree-sitter-perl/tree-sitter-perl
//! [`perl-parser`]: https://docs.rs/perl-parser
//! [`tree-sitter-perl-rs`]: https://docs.rs/tree-sitter-perl-rs

use std::path::Path;
use tree_sitter::{Language, Parser};

/// Returns the tree-sitter [`Language`] for Perl (C grammar).
///
/// Use this to configure a [`tree_sitter::Parser`] or to create query objects
/// that target the Perl grammar.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::language;
/// use tree_sitter::Parser;
///
/// let lang = language();
/// let mut parser = Parser::new();
/// parser.set_language(&lang).unwrap();
/// ```
pub fn language() -> Language {
    // SAFETY: `tree_sitter_perl` is generated by tree-sitter-cli and linked via `build.rs`.
    // It returns a valid, 'static `Language` value representing the Perl grammar. The function
    // has no preconditions on the calling thread, takes no arguments, holds no borrows, and
    // cannot cause aliasing or memory-safety issues. Soundness depends on the build script
    // linking the correct, ABI-compatible parser object, which cc::Build in build.rs guarantees.
    unsafe { tree_sitter_perl() }
}

/// Creates a [`tree_sitter::Parser`] configured for Perl.
///
/// Returns an error if the language version is incompatible with the linked
/// tree-sitter runtime (this should not happen in practice).
///
/// Prefer this over [`create_parser`] in new code — it surfaces errors
/// explicitly.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::try_create_parser;
///
/// let mut parser = try_create_parser().unwrap();
/// let tree = parser.parse("my $x = 1;", None).unwrap();
/// assert!(!tree.root_node().has_error());
/// ```
pub fn try_create_parser() -> Result<Parser, tree_sitter::LanguageError> {
    let mut parser = Parser::new();
    parser.set_language(&language())?;
    Ok(parser)
}

/// Creates a [`tree_sitter::Parser`] configured for Perl, silently ignoring
/// language-set errors.
///
/// This is a compatibility shim. Prefer [`try_create_parser`] in new code so
/// that version mismatches are not swallowed.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::create_parser;
///
/// let parser = create_parser();
/// assert!(parser.language().is_some());
/// ```
pub fn create_parser() -> Parser {
    let mut parser = Parser::new();
    let _ = parser.set_language(&language());
    parser
}

/// Parses a Perl source string and returns the resulting [`tree_sitter::Tree`].
///
/// # Errors
///
/// Returns an error if the parser cannot be initialised (version mismatch) or
/// if tree-sitter returns `None` from `parse` (cancelled or timed out).
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::parse_perl_code;
///
/// let tree = parse_perl_code("my $x = 42;").unwrap();
/// assert!(!tree.root_node().has_error());
/// ```
pub fn parse_perl_code(code: &str) -> Result<tree_sitter::Tree, Box<dyn std::error::Error>> {
    let mut parser = try_create_parser()?;
    match parser.parse(code, None) {
        Some(tree) => Ok(tree),
        None => Err("Failed to parse code".into()),
    }
}

/// Reads a file from `path` and parses it as Perl source.
///
/// # Errors
///
/// Returns an error if the file cannot be read or if parsing fails (see
/// [`parse_perl_code`]).
pub fn parse_perl_file<P: AsRef<Path>>(
    path: P,
) -> Result<tree_sitter::Tree, Box<dyn std::error::Error>> {
    let code = std::fs::read_to_string(path)?;
    parse_perl_code(&code)
}

/// Returns the scanner backend identifier for this crate.
///
/// Always returns `"c-scanner"`. Useful when code needs to distinguish between
/// this crate and the Rust-native [`tree-sitter-perl-rs`] backend.
///
/// [`tree-sitter-perl-rs`]: https://docs.rs/tree-sitter-perl-rs
pub fn get_scanner_config() -> &'static str {
    "c-scanner"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_language_loading() {
        let lang = language();
        let count = lang.node_kind_count();
        println!("C implementation node kind count: {}", count);
        // Language is valid if we can get its node kind count
        assert!(count > 0);
    }

    #[test]
    fn test_basic_parsing() -> Result<(), Box<dyn std::error::Error>> {
        let code = "my $var = 'hello';";
        let tree = parse_perl_code(code)?;
        assert!(!tree.root_node().has_error());
        Ok(())
    }

    #[test]
    fn test_parser_creation() {
        let parser = create_parser();
        assert!(parser.language().is_some());
    }
}

// SAFETY: See the SAFETY comment on the `language()` function above.
// This is the only unsafe code in the crate — the single FFI symbol we need
// from the compiled C grammar. No bindgen is used; the declaration is
// hand-written to avoid a libclang build dependency.
unsafe extern "C" {
    fn tree_sitter_perl() -> Language;
}
