//! Tree-sitter Perl grammar binding (C FFI).
//!
//! This crate is the conventional C/tree-sitter reference implementation for
//! Perl, maintained alongside the native v3 Rust parser ([`perl-parser`]) for
//! compatibility testing and comparison. It vendors a snapshot of the upstream
//! [tree-sitter-perl] C grammar (`parser.c` + `scanner.c`) under `c-src/` and
//! exposes it via a hand-written FFI declaration — no `bindgen` or `libclang`
//! dependency is required to build.
//!
//! ## Relation to `tree-sitter-perl-rs`
//!
//! [`tree-sitter-perl-rs`] is a thin facade over the native v3 Rust parser and
//! is the recommended choice for new Rust projects. This crate (`tree-sitter-perl-c`)
//! should be preferred when:
//!
//! - **Compatibility testing** — comparing parse output against the upstream
//!   C reference grammar.
//! - **Non-Rust tree-sitter tooling** — the C grammar snapshot can be used as
//!   a build dependency for language bindings in other languages.
//! - **Baseline benchmarking** — measuring parse throughput of the C grammar
//!   against the native v3 parser.
//!
//! ## Build requirements
//!
//! Only a C compiler is required (e.g., `cc`/`gcc`/`clang` on Linux/macOS,
//! MSVC or MinGW on Windows). No `libclang` or `bindgen` toolchain is needed.
//!
//! ## Quick start
//!
//! ```rust
//! use tree_sitter_perl_c::parse_perl_code;
//!
//! let tree = parse_perl_code("my $x = 42;").unwrap();
//! assert!(!tree.root_node().has_error());
//! println!("{}", tree.root_node().to_sexp());
//! ```
//!
//! [tree-sitter-perl]: https://github.com/tree-sitter-perl/tree-sitter-perl
//! [`perl-parser`]: https://docs.rs/perl-parser
//! [`tree-sitter-perl-rs`]: https://docs.rs/tree-sitter-perl-rs

use std::{fmt, path::Path};
use tree_sitter::{Language, Parser};

/// Error returned by [`parse_perl_code`] and [`parse_perl_file`].
#[derive(Debug)]
#[non_exhaustive]
pub enum ParseError {
    /// The parser could not be configured with the linked language/runtime pair.
    Language(tree_sitter::LanguageError),
    /// tree-sitter returned `None` from `parse` (cancelled parse or timeout).
    ParseCancelled,
    /// File I/O error while reading source from disk.
    Io(std::io::Error),
}

impl fmt::Display for ParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ParseError::Language(err) => {
                write!(f, "failed to configure Perl parser language: {err}")
            }
            ParseError::ParseCancelled => {
                write!(f, "failed to parse code: parse was cancelled or timed out")
            }
            ParseError::Io(err) => write!(f, "failed to read Perl source file: {err}"),
        }
    }
}

impl std::error::Error for ParseError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ParseError::Language(err) => Some(err),
            ParseError::ParseCancelled => None,
            ParseError::Io(err) => Some(err),
        }
    }
}

/// Returns the tree-sitter [`Language`] for Perl (C grammar).
///
/// Use this to configure a [`tree_sitter::Parser`] or to create query objects
/// that target the Perl grammar.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::language;
/// use tree_sitter::Parser;
///
/// let lang = language();
/// let mut parser = Parser::new();
/// parser.set_language(&lang).unwrap();
/// ```
pub fn language() -> Language {
    // SAFETY: `tree_sitter_perl` is generated by tree-sitter-cli and linked via `build.rs`.
    // It returns a valid, 'static `Language` value representing the Perl grammar. The function
    // has no preconditions on the calling thread, takes no arguments, holds no borrows, and
    // cannot cause aliasing or memory-safety issues. Soundness depends on the build script
    // linking the correct, ABI-compatible parser object, which cc::Build in build.rs guarantees.
    unsafe { tree_sitter_perl() }
}

/// Creates a [`tree_sitter::Parser`] configured for Perl.
///
/// Returns an error if the language version is incompatible with the linked
/// tree-sitter runtime (this should not happen in practice).
///
/// Prefer this over [`create_parser`] in new code — it surfaces errors
/// explicitly.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::try_create_parser;
///
/// let mut parser = try_create_parser().unwrap();
/// let tree = parser.parse("my $x = 1;", None).unwrap();
/// assert!(!tree.root_node().has_error());
/// ```
pub fn try_create_parser() -> Result<Parser, tree_sitter::LanguageError> {
    let mut parser = Parser::new();
    parser.set_language(&language())?;
    Ok(parser)
}

/// Creates a [`tree_sitter::Parser`] configured for Perl, silently ignoring
/// language-set errors.
///
/// This is a compatibility shim. Prefer [`try_create_parser`] in new code so
/// that version mismatches are not swallowed.
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::create_parser;
///
/// let parser = create_parser();
/// assert!(parser.language().is_some());
/// ```
pub fn create_parser() -> Parser {
    let mut parser = Parser::new();
    let _ = parser.set_language(&language());
    parser
}

/// Parses a Perl source string and returns the resulting [`tree_sitter::Tree`].
///
/// # Errors
///
/// Returns an error if the parser cannot be initialised (version mismatch) or
/// if tree-sitter returns `None` from `parse` (cancelled or timed out).
///
/// # Example
///
/// ```rust
/// use tree_sitter_perl_c::parse_perl_code;
///
/// let tree = parse_perl_code("my $x = 42;").unwrap();
/// assert!(!tree.root_node().has_error());
/// ```
pub fn parse_perl_code(code: &str) -> Result<tree_sitter::Tree, ParseError> {
    let mut parser = try_create_parser().map_err(ParseError::Language)?;
    match parser.parse(code, None) {
        Some(tree) => Ok(tree),
        None => Err(ParseError::ParseCancelled),
    }
}

/// Reads a file from `path` and parses it as Perl source.
///
/// The file is read as raw bytes, so non-UTF-8 Perl source files (e.g. those
/// containing Latin-1 comments or string literals) are handled correctly.
///
/// # Errors
///
/// - [`ParseError::Io`] — if the file cannot be read (not found, permission denied, etc.)
/// - [`ParseError::Language`] — if the parser cannot be configured (grammar version mismatch)
/// - [`ParseError::ParseCancelled`] — if tree-sitter returns `None` (cancelled or timed out)
pub fn parse_perl_file<P: AsRef<Path>>(path: P) -> Result<tree_sitter::Tree, ParseError> {
    let bytes = std::fs::read(path).map_err(ParseError::Io)?;
    let mut parser = try_create_parser().map_err(ParseError::Language)?;
    parser.parse(bytes.as_slice(), None).ok_or(ParseError::ParseCancelled)
}

/// Returns the scanner backend identifier for this crate.
///
/// Always returns `"c-scanner"`. Useful when code needs to distinguish between
/// this crate and the Rust-native [`tree-sitter-perl-rs`] backend.
///
/// [`tree-sitter-perl-rs`]: https://docs.rs/tree-sitter-perl-rs
pub fn get_scanner_config() -> &'static str {
    "c-scanner"
}

#[cfg(test)]
mod tests {
    use super::*;
    use tree_sitter::{Query, QueryCursor, StreamingIterator};

    const INJECTIONS_QUERY: &str = include_str!("../../../tree-sitter-perl/queries/injections.scm");

    fn capture_text<'a>(
        query: &'a Query,
        code: &'a str,
        capture: tree_sitter::QueryCapture<'a>,
    ) -> Option<(&'a str, &'a str)> {
        let name = query.capture_names().get(capture.index as usize)?;
        let text = capture.node.utf8_text(code.as_bytes()).ok()?;
        Some((*name, text))
    }

    #[test]
    fn test_language_loading() {
        let lang = language();
        let count = lang.node_kind_count();
        println!("C implementation node kind count: {}", count);
        // Language is valid if we can get its node kind count
        assert!(count > 0);
    }

    #[test]
    fn test_basic_parsing() -> Result<(), Box<dyn std::error::Error>> {
        let code = "my $var = 'hello';";
        let tree = parse_perl_code(code)?;
        assert!(!tree.root_node().has_error());
        Ok(())
    }

    #[test]
    fn test_parser_creation() {
        let parser = create_parser();
        assert!(parser.language().is_some());
    }

    #[test]
    fn test_inline_cpp_injection_query_matches_heredoc_body()
    -> Result<(), Box<dyn std::error::Error>> {
        let code = "use Inline CPP => <<'END_CPP';\n#include <string>\nclass Greet {};\nEND_CPP\n";
        let tree = parse_perl_code(code)?;
        let query = Query::new(&language(), INJECTIONS_QUERY)?;
        let mut cursor = QueryCursor::new();

        let mut matched = false;
        let mut matches = cursor.matches(&query, tree.root_node(), code.as_bytes());
        while let Some(m) = matches.next() {
            let mut saw_inline_package = false;
            let mut saw_inline_language = false;
            let mut saw_injection_content = false;

            for capture in m.captures {
                if let Some((name, text)) = capture_text(&query, code, *capture) {
                    match name {
                        "inline.package" => saw_inline_package = text == "Inline",
                        "inline.language" => saw_inline_language = text == "CPP",
                        "injection.content" => {
                            saw_injection_content = capture.node.kind() == "heredoc_content"
                                && text.contains("#include <string>");
                        }
                        _ => {}
                    }
                }
            }

            if saw_inline_package && saw_inline_language && saw_injection_content {
                matched = true;
                break;
            }
        }

        assert!(matched, "expected Inline::CPP heredoc to match the injection query");
        Ok(())
    }

    #[test]
    fn test_parse_perl_file_reports_io_errors() {
        let missing = std::env::temp_dir().join("tree_sitter_perl_c_missing_input_for_io_error.pl");
        let result = parse_perl_file(&missing);
        assert!(matches!(result, Err(ParseError::Io(_))));
    }

    /// Verify that `ParseError::Display` covers all variants and produces
    /// non-empty messages.  This guards against silent silencing of error info
    /// if a new variant is added without a `fmt` arm.
    #[test]
    fn test_parse_error_display_is_non_empty_for_all_variants() {
        use std::io;
        let io_err = ParseError::Io(io::Error::new(io::ErrorKind::NotFound, "missing"));
        assert!(!io_err.to_string().is_empty(), "Io variant must have a Display message");

        let cancelled = ParseError::ParseCancelled;
        assert!(
            !cancelled.to_string().is_empty(),
            "ParseCancelled variant must have a Display message"
        );

        // Language variant requires a real LanguageError; verify the Io and Cancelled
        // variants are sufficient to confirm the Display impl compiles and runs.
    }

    /// Verify that `parse_perl_file` accepts a file containing non-UTF-8 bytes
    /// (e.g. Latin-1 encoded comments) without returning an Io error.
    #[test]
    fn test_parse_perl_file_accepts_non_utf8_bytes() -> Result<(), Box<dyn std::error::Error>> {
        let path =
            std::env::temp_dir().join("tree_sitter_perl_c_non_utf8_parse_error_test.pl");
        // Latin-1 byte 0xE9 ('é') embedded in a comment — valid Perl, invalid UTF-8
        let source = b"# caf\xE9\nmy $x = 1;\n";
        std::fs::write(&path, source)?;
        let result = parse_perl_file(&path);
        let _ = std::fs::remove_file(&path);
        // Should succeed — tree-sitter handles raw bytes
        assert!(result.is_ok(), "parse_perl_file should handle non-UTF-8 bytes, got: {result:?}");
        Ok(())
    }
}

// SAFETY: See the SAFETY comment on the `language()` function above.
// This is the only unsafe code in the crate — the single FFI symbol we need
// from the compiled C grammar. No bindgen is used; the declaration is
// hand-written to avoid a libclang build dependency.
unsafe extern "C" {
    fn tree_sitter_perl() -> Language;
}
