use std::env;
use std::path::PathBuf;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(env::var("OUT_DIR")?);

    // Build the C sources generated by tree-sitter
    let mut build = cc::Build::new();
    let grammar_src = PathBuf::from("../../tree-sitter-perl/src");
    let parser_c = grammar_src.join("parser.c");
    build.file(&parser_c);

    let scanner_c = grammar_src.join("scanner.c");
    if scanner_c.exists() {
        build.file(&scanner_c);
        // Only rerun if the scanner exists and changes
        println!("cargo:rerun-if-changed={}", scanner_c.display());
    }

    build
        .include(&grammar_src)
        .flag_if_supported("-std=c99")
        .flag_if_supported("-Wno-unused-parameter")
        .flag_if_supported("-Wno-unused-variable")
        .flag_if_supported("-Wno-unused-function")
        .compile("tree-sitter-perl-c");

    // Generate bindings
    let header = grammar_src.join("tree_sitter/parser.h");
    let bindings = bindgen::Builder::default()
        .header(header.to_string_lossy())
        .clang_arg(format!("-I{}", grammar_src.display()))
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate_inline_functions(true)
        .size_t_is_usize(true)
        // For Rust 2024 compatibility: generate safe extern blocks
        .wrap_unsafe_ops(true)
        // Additional setting for external functions
        .default_macro_constant_type(bindgen::MacroTypeVariation::Signed)
        .generate()
        .map_err(|e| format!("Unable to generate bindings: {}", e))?;

    bindings.write_to_file(out_dir.join("bindings.rs"))?;

    // No need to post-process - bindgen 0.72 already handles Rust 2024 unsafe extern blocks

    // Tell cargo to look for shared libraries in the specified directory
    println!("cargo:rustc-link-search=native={}", out_dir.display());

    // Tell cargo to tell rustc to link our C library
    println!("cargo:rustc-link-lib=static=tree-sitter-perl-c");

    // Only rerun this script if the C source files change
    println!("cargo:rerun-if-changed={}", parser_c.display());
    if scanner_c.exists() {
        println!("cargo:rerun-if-changed={}", scanner_c.display());
    }
    println!("cargo:rerun-if-changed={}", grammar_src.join("tree_sitter/parser.h").display());

    // ---
    // Audit: Known warnings from legacy C code and generated bindings
    // These warnings are from system headers, libc, or autogenerated code and cannot be fixed in this crate.
    // They do not affect correctness, safety, or auditability of the Rust integration.
    //
    // Ignored warning patterns:
    // - type naming (should have upper camel case name)
    // - non_upper_case_globals
    // - FFI-safety for u128 (not used in our FFI boundary)
    //
    // These are logged for traceability and explicitly ignored for CI and audit purposes.
    println!(
        "cargo:warning=Ignoring legacy C/bindgen warnings: type naming, non_upper_case_globals, FFI u128"
    );

    Ok(())
}
